### ISSUE TITLE
Typing next/navigation

### ISSUE THREAD

**Issue by litewarp** [tatethurston/nextjs-routes#105]
Apologies for multiple issues this week. Trying to type all the things with the new next13. 

I notice that `useRouter` is typed only from the `next/link` import and not the new [`next/navigation` module](https://beta.nextjs.org/docs/api-reference/use-router#userouter), and I was wondering if it will be supported in the future.

Thanks for the great package!

**Comment by tatethurston** [comment]
@litewarp No apologies necessary, I appreciate you taking the time to open issues. It’s easy to encounter a rough edge in a library and move on without giving any feedback.

Thank you for pointing that out, I can certainly add support for next/navigation in the next few days.

**Comment by tatethurston** [comment]
Hey @litewarp I did some investigation here and Next's app directory now uses strings for Link and useRouter -- removing the ability to use the `UrlObject` form. 
https://github.com/vercel/next.js/discussions/41745#discussioncomment-4239793

**Comment by tatethurston** [comment]
A workaround is using `route` from `nextjs-routes`: https://github.com/tatethurston/nextjs-routes#what-if-i-need-a-runtime. Eg:

```tsx
import { useRouter } from 'next/navigation';

useRouter.push(route({ pathname: "/api/foos/[foo]", query: { foo: "foobar" } }));
```

**Comment by tatethurston** [comment]
Closing because this reflects the API that the nextjs team chose for the new `app` directory. If you would like to see this implemented, you can voice that [here](https://github.com/vercel/next.js/discussions/41745#discussioncomment-4239793). I'm happy to revisit this if `next/navigation` becomes type-able beyond `string`

**Comment by tatethurston** [comment]
NextJS now supports this via an experimental configuration option: https://beta.nextjs.org/docs/configuring/typescript#statically-typed-links

**Comment by tatethurston** [comment]
If there is sufficient interest in porting this functionality to nextjs-routes I'll look into it, but my current recommendation is that folks use next's builtin capability. Note: this only applies to `app` directory routes -- there is not route type generation for `pages` directory.

**Comment by tran-simon** [comment]
would be great for those who cant migrate to next 13

**Comment by tatethurston** [comment]
@tran-simon next/navigation comes from next13, could you explain your use case?

**Comment by tran-simon** [comment]
I'm on next12, I would like a way to type search parameters.

**Comment by tatethurston** [comment]
@tran-simon can you provide a code example?

**Comment by tran-simon** [comment]
For path `www.myapp.com/organization/myorg?user=user
```
  const { query, push } = useRouter();

  const {user} = query

  // ...

  push({
    query: {
      user: 'test'
    }
  })
  ```

It would be great to have user strongly typed. That way, if in the future I rename user to something else typescript will complain if I forget to rename it in some places

**Comment by tatethurston** [comment]
@tran-simon did you mean to post on  https://github.com/tatethurston/nextjs-routes/issues/39 instead ?
