### ISSUE TITLE
useRouter `push` function miss the property `pathname`

### ISSUE THREAD

**Issue by ChristoRibeiro** [tatethurston/nextjs-routes#106]
Great lib and great work on that! 

I'm using the [nextjs-routes v1.0.4](https://github.com/tatethurston/nextjs-routes/releases/tag/v1.0.4) and in the README example : 

```ts
import { useRouter } from "next/link";

const router = useRouter();
router.push({ pathname: "/foos/[foo]", query: { foo: "test" } });
```

1. the import should be `from "next/router"`
2. the property `pathname` from `router.push` is not available but `query` does.

Can you confirm @tatethurston ?

**Comment by ChristoRibeiro** [comment]
The [core.ts#L230 ](https://github.com/tatethurston/nextjs-routes/blob/main/src/core.ts#L230) should get this change?

```diff
push(
-  url: { query?: { [key: string]: string | string[] | undefined } },
+   url: {
+     pathname: Route,
+     query?: { [key: string]: string | string[] | undefined }
+  }, 
  as?: string,
  options?: TransitionOptions
): Promise<boolean>;
```

**Comment by ChristoRibeiro** [comment]
Looks like `<Link href={{ ... }}` miss too the `pathname` property.

**Comment by tatethurston** [comment]
> The [core.ts#L230 ](https://github.com/tatethurston/nextjs-routes/blob/main/src/core.ts#L230) should get this change?
> 
> ```diff
> push(
> -  url: { query?: { [key: string]: string | string[] | undefined } },
> +   url: {
> +     pathname: Route,
> +     query?: { [key: string]: string | string[] | undefined }
> +  }, 
>   as?: string,
>   options?: TransitionOptions
> ): Promise<boolean>;
> ```

No -- `push` is overloaded, if you look at the first function definition push already accepts `pathname`: https://github.com/tatethurston/nextjs-routes/blob/main/src/core.ts#L220

**Comment by tatethurston** [comment]
> the import should be from "next/router"

Thanks for noticing this, I've updated the readme.

**Comment by ChristoRibeiro** [comment]
So how can I use push with a pathname and query? 

My use case:

router.push({
  pathname: "/product-data",
  query: { 
    id: "123",
    sort: "desc",
    groupBy: "name"
  }
})

**Comment by tatethurston** [comment]
@ChristoRibeiro You can use both `pathname` and `query`, see the example I referenced previously: https://stackblitz.com/edit/nextjs-88s7s8?file=pages%2Froute-a.tsx,pages%2Findex.tsx

**Comment by ChristoRibeiro** [comment]
If I use `push` with a string as a parameter, `pathname` is recognized: `push("/data")` but if I use `push` with an object as a parameter, pathname is missing:

![CleanShot 2022-11-28 at 13 29 01](https://user-images.githubusercontent.com/743358/204278340-cbfad30d-c4c6-4884-a176-9d398c4e0e0e.gif)

And here the error description:

<img width="790" alt="CleanShot 2022-11-28 at 13 31 21@2x" src="https://user-images.githubusercontent.com/743358/204278543-222d74b7-10df-49f6-8cb5-46805e6c78fd.png">

I guess it's not the correct behaviour as mentioned in the documentation @tatethurston?

**Comment by ChristoRibeiro** [comment]
I updated to Nextjs 13 and it work now 🙌
