### ISSUE TITLE
Handling Catch All Routes

### ISSUE THREAD

**Issue by JameelKhan9** [tatethurston/nextjs-routes#109]
Love the type-safe routes!

However, I am having issues using the features nextjs-routes makes available with Catch All Routes:
https://nextjs.org/docs/api-routes/dynamic-api-routes#catch-all-api-routes

This comes around due to some SDKs requiring catch alls or optional catch alls:
https://github.com/auth0/nextjs-auth0#add-the-dynamic-api-route

Probably not an easy one to fix, but would be really powerful to be able to handle catch-all routes.

**Comment by tatethurston** [comment]
Hey @JameelKhan9 could you share the error you’re seeing and your Nextjs-routes.d.ts file?

**Comment by tatethurston** [comment]
@JameelKhan9 This is already supported. Feel free to reopen this with reproduction steps if you're still seeing this issue.

**Comment by JameelKhan9** [comment]
@tatethurston I just had another look, and I managed to get it to work. I think the usage of catch-all routes wasn't as intuitive the first time I looked at it.

Cheers!
