### ISSUE TITLE
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module needs an import assertion of type "json"

### ISSUE THREAD

**Issue by cktsun1031** [tatethurston/nextjs-routes#115]
Error Occurred:
![image](https://user-images.githubusercontent.com/65409152/210753093-387299b8-6421-4e2b-be30-fd7519dd7615.png)

To Reproduce this problem:

1. Use Module as project `type`
```js
   "type": "module"
```

2. Run `dev`

**Comment by tatethurston** [comment]
Thanks for reporting @cktsun1031. I'm publishing v1.0.7 now to resolve this.

I've updated one of the examples to use `"type": "module"` to prevent this class of errors in the future.
