### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by statusunknown418** [tatethurston/nextjs-routes#118]
<img width="694" alt="Screenshot 2023-01-19 at 12 45 03" src="https://user-images.githubusercontent.com/74371045/213520548-d620b0df-d791-4b9c-b506-0df0a5bb141a.png">

VSCode seems no to be finding the types required for the package, `pnpm add @types/nextjs-routes` package doesn't exist as well

**Comment by tatethurston** [comment]
The types ship with the package. @types/nextjs-routes does not exist.

It looks like you’re trying to import the cjs module into mjs, which isn’t valid. Could you let me know if the issue persists if you import nextjs-routes/config or nextjs-routes/config.mjs?

**Comment by AlvaroAquijeDiaz** [comment]
the error is still present, I changed my next config to `.config.js` and used `nextjs-routes/config` but throws the error of no declarations found

**Comment by tatethurston** [comment]
Thanks for reporting @AlvaroAquijeDiaz. This has been fixed in v1.0.8.
