### ISSUE TITLE
Syntax error on .d.ts generated file

### ISSUE THREAD

**Issue by erickriva** [tatethurston/nextjs-routes#13]
Generated code has a little mistake 😅
Slashes were inverted.

![image](https://user-images.githubusercontent.com/2746558/177056373-c51602fd-e233-406b-892a-83e180e3da42.png)

**Comment by tatethurston** [comment]
Thanks for reporting @erickriva. What OS are you using — is it Windows?

**Comment by erickriva** [comment]
> Thanks for reporting @erickriva. What OS are you using — is it Windows?

Windows 11, with Next 12.0.* and Node 16.*

**Comment by tatethurston** [comment]
@erickriva I've released v0.0.12 with the fix, LMK if you run into any issues.

**Comment by erickriva** [comment]
It worked well! 🎉
Thank you!
