### ISSUE TITLE
'Module not found' error

### ISSUE THREAD

**Issue by erickriva** [tatethurston/nextjs-routes#14]
`yarn` was run, but this error still pops... any idea why?

![image](https://user-images.githubusercontent.com/2746558/177057431-55f7a1f0-d757-4876-8ca4-72de991d0b52.png)

**Comment by tatethurston** [comment]
Can you let me know which version of next you’re using? I _think_ this could be related to the latest next upgrade, I have an outstanding todo to look at the changes made to next/link, previous next releases included babel interop code that resulted in the default export being default.default under ESM.

**Comment by erickriva** [comment]
using next 12.2.0 here, latest release...
if i can help you with it, you can just tell me

**Comment by tatethurston** [comment]
@erickriva I've released v0.0.12 with the fix, LMK if you run into any issues.

**Comment by erickriva** [comment]
It worked well! 🎉
