### ISSUE TITLE
Nextjs@13 not supported dynamic href in the /app directory

### ISSUE THREAD

**Issue by po4tion** [tatethurston/nextjs-routes#142]
First, If you are considering this, I am sorry for registering the issue.

When I run the examples/app folder(nextjs version is 13.3.0), I get the following error.

![image](https://user-images.githubusercontent.com/55759551/231062995-ad990185-1ea9-479c-9e5b-a9de03685fbe.png)

[Link: Next.js Error Occurred](https://nextjs.org/docs/messages/app-dir-dynamic-href)

If you go to the link provided above, next.js says that url mapping is no longer available for the app directory structure.

[example code]
```tsx
<Link href={{ pathname: "/[store]", query: { store: "tate" } }}>
  Tate's Store
</Link>
```

I think we need to figure out a way to use it in the app directory of Next.js@13.

If there's anything I made a mistake, please give me some advice!

**Comment by tatethurston** [comment]
Yes, the nextjs team removed support for the `UrlObject` form for `Link` with the `app` directory. Are you using the `pages` directory, the `app` directory, or both in your project?

**Comment by po4tion** [comment]
i'm using the app directory only.

**Comment by tatethurston** [comment]
Have you tried https://nextjs.org/blog/next-13-2#statically-typed-links? This library supports the `pages` directory, but nextjs now ships typescript support for the app directory

**Comment by po4tion** [comment]
> Have you tried https://nextjs.org/blog/next-13-2#statically-typed-links? This library supports the `pages` directory, but nextjs now ships typescript support for the app directory

Thank you for your help. The "typed Routes" function works very well.

**Comment by tatethurston** [comment]
Now supported in [2.2.2](https://www.npmjs.com/package/nextjs-routes/v/2.2.2)
