### ISSUE TITLE
Is there a setting when using Next.js 13?

### ISSUE THREAD

**Issue by ilarkShim** [tatethurston/nextjs-routes#158]
When using Next.js 13, is there a setting to enable the use of path strings when configured under the app folder?

**Comment by tatethurston** [comment]
@ilarkShim does your application exclusively use the app directory? 

https://github.com/tatethurston/nextjs-routes/issues/142#issuecomment-1504326765

**Comment by ilarkShim** [comment]
Only the app directory is being used. It consists of route.ts and page.tsx in subdirectories of the app directory.

**Comment by ilarkShim** [comment]
> @ilarkShim does your application exclusively use the app directory?
> 
> [#142 (comment)](https://github.com/tatethurston/nextjs-routes/issues/142#issuecomment-1504326765)

Only the app directory is being used. It consists of route.ts and page.tsx in subdirectories of the app directory.

**Comment by tatethurston** [comment]
Now supported in [2.2.2](https://www.npmjs.com/package/nextjs-routes/v/2.2.2)
