### ISSUE TITLE
Unable to resolve nextjs-routes/config though working

### ISSUE THREAD

**Issue by mehdimahmoudi** [tatethurston/nextjs-routes#163]
Hi,
First things first, thank you for this great tool! Amazing and accurate work.

I'm facing a dependency resolution issue that's keeping me from building the project without having to comment / disable the nextjs-routes require line.

Important to note that although the module is not resolved and ESLinting showing an error, it still works perfectly and generates routes at the right location as expected.

Any clue?

Thanks!

<img width="495" alt="image" src="https://github.com/tatethurston/nextjs-routes/assets/209687/abc50b8e-5755-4427-82a1-fbd95ca532bd">

**Comment by tatethurston** [comment]
@mehdimahmoudi could you share the error you’re encountering?

**Comment by mehdimahmoudi** [comment]
@tatethurston 

I get this linting error: `Unable to resolve path to module 'nextjs-routes/config'` also keeping me from building the app.

<img width="1072" alt="image" src="https://github.com/tatethurston/nextjs-routes/assets/209687/2b7c724e-3a81-4f2b-b8ab-c29aafcd09dc">

But I don't think it's just a linting because other requires work well.

Here's my `next.config.js `file

```js
// @ts-check

// @TODO: Cannot be imported or built with
const nextRoutes = require('nextjs-routes/config');

const withRoutes = nextRoutes();
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});
const { i18n } = require('./next-i18next.config');

// Route typing
const withRoutes = nextRoutes({ outDir: 'src/types/routes', cwd: __dirname });

/**
 * @type {import('next').NextConfig}
 **/
const baseConfig = withBundleAnalyzer({
  reactStrictMode: false,
  i18n,
  eslint: {
    ignoreDuringBuilds: true,
  },
});

module.exports = withRoutes(baseConfig);
```

Thanks

**Comment by tatethurston** [comment]
@mehdimahmoudi Do you encounter any typescript errors? Eg running tsc —noEmit?

Also, could you update your ESLint dependencies to make sure they’re not outdated

**Comment by mehdimahmoudi** [comment]
@tatethurston 

Just updated to ESLInt 8.42 (yesterday 8.41

`npx tsc --noEmit` still gives:

![image](https://github.com/tatethurston/nextjs-routes/assets/209687/03cffe0f-128e-4e06-a508-f9455f82aac0)

**Comment by tatethurston** [comment]
@mehdimahmoudi I believe this is an issue with your local dependencies and not this library. I'm sorry for the unsatisfying answer. 

To debug this on your end, you could start by copying one of the [examples](https://github.com/tatethurston/nextjs-routes/tree/main/examples) -- like the typescript example -- locally and seeing if you still encounter the error (you shouldn't). From there you can compare your dependencies to the example project dependencies to narrow it down.
