### ISSUE TITLE
Generate .d.ts file during build also

### ISSUE THREAD

**Issue by ecstrema** [tatethurston/nextjs-routes#164]
It seems that only next dev generates the file, but next build does not, so if I .gitignore the generated typings, build fails on CI.

I read in the readme that the route typings are generated during build also, but cannot reproduce this.

### to reproduce

- Delete the nextjs-routes.d.ts file
- Run `next build` 
- typings are not created

Since typings are not created, the typescript build fails if we

```ts
import type { Route } from "nextjs-routes";
```

### expected

The file is also generated during build

**Comment by tatethurston** [comment]
@ecstrema the nextjs-routes.d.ts is generated into types/nextjs-routes.d.ts.

you can not gitignore this file because typechecking occurs before the build step runs in nextjs.

**Comment by ecstrema** [comment]
Hmm that's interesting... The best way might be to run the generating cli before build then...

**Comment by ecstrema** [comment]
So for those wanting a fix: here's what I did:

package.json: 

```json

**Comment by tatethurston** [comment]
Yep, alternatively you could disable typechecking in your next.config.js and then run tsc —noEmit after you build.
