### ISSUE TITLE
Support next.config.cjs, next.config.mjs

### ISSUE THREAD

**Issue by insik-han** [tatethurston/nextjs-routes#165]
Hi

Thank you for your development.
This library is very useful

But It dosen't work to next.config.cjs and next.config.mjs

Any Plan to update?

**Comment by tatethurston** [comment]
@insik-han This library should work with both next.config.cjs and next.config.mjs already. If you look at the examples, you’ll see next.config.mjs used.

What is the issue you’re running into?

**Comment by insik-han** [comment]
When I try to next.config.cjs, It dosen't create nextjs-routers.d.ts.
Here's my code
![image](https://github.com/tatethurston/nextjs-routes/assets/63291908/eecf41cc-6510-400a-98c0-3ea92cff32b9)
But next.config.mjs is works. Sorry. There is problem in next.config.cjs

**Comment by tatethurston** [comment]
@insik-han There is also an example using commonjs (the typescript example). Can you share the error you're encountering?
