### ISSUE TITLE
Library not working with the NextJS 13 app folder

### ISSUE THREAD

**Issue by byronthe123** [tatethurston/nextjs-routes#167]
I was using this library with NextJS 13 using the `pages` folder and it worked perfectly. However, after changing to the new `app` folder, the `routes` in `/ypes/nextjs-routes.d.ts`  are not being generated correctly. Here's an example of the output:
```  
export type Route =
    | StaticRoute<"/">
    | StaticRoute<"/">
    | StaticRoute<"/">;
```

**Comment by tatethurston** [comment]
This package supports the `pages` directory, but nextjs ships typescript support for the `app` directory, which you can use instead of this package:

 https://nextjs.org/blog/next-13-2#statically-typed-links?

**Comment by tatethurston** [comment]
Now supported in [2.2.2](https://www.npmjs.com/package/nextjs-routes/v/2.2.2)
