### ISSUE TITLE
Allow trailling slashes

### ISSUE THREAD

**Issue by piotrgrundas** [tatethurston/nextjs-routes#168]
Currently, the lib [always strips the trailing slashes](https://github.com/tatethurston/nextjs-routes/blob/main/packages/nextjs-routes/src/core.ts#L339C16-L339C16) when using `route` function.

I would expect that it respects the next config `trailingSlash` or at least respect some flag for determining if the trailing slash should be stripped or not.

This leads to unnecessary redirects if someone uses `trailingSlash: true`.

**Comment by tatethurston** [comment]
Thanks @piotrgrundas agreed that the ideal behavior is to use the next config value. I’d accept a PR for this. 

Alternatively, I’ll look into this when I have time.
