### ISSUE TITLE
needs update for next 13

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [tatethurston/nextjs-routes#169]
the `router` is now also available through `next/navigation`, plus next includes another function: `redirect` that also accepts a path and should be typed

**Comment by tatethurston** [comment]
The API for the next navigation router is quite a bit different. I recommend using nexts route type generation if you’re using next 13

**Comment by tatethurston** [comment]
Now supported in [2.2.2](https://www.npmjs.com/package/nextjs-routes/v/2.2.2)
