### ISSUE TITLE
File generation problem

### ISSUE THREAD

**Issue by AkanoCA** [tatethurston/nextjs-routes#187]
Hello!
File type is not generated correctly on Windows 11
All paths are replaced with a single slash
![image](https://github.com/tatethurston/nextjs-routes/assets/55537294/33b92ab0-8f4a-49de-8490-67676a89c77c)

I tried for a long time to find what the problem was, but it seems I finally found it

![image](https://github.com/tatethurston/nextjs-routes/assets/55537294/1a5c9b35-0151-45e9-8956-57e3e8c69dd9)

I would be very grateful if you could fix this problem one way or another

**Comment by tatethurston** [comment]
Hey thanks for reporting. I’d be happy to accept a PR to correct the path behavior.

Are you using the app directory? If so, checkout https://github.com/tatethurston/nextjs-routes/issues/170
