### ISSUE TITLE
[Question] 'Rewrites' support

### ISSUE THREAD

**Issue by erickriva** [tatethurston/nextjs-routes#19]
Hello 🙂! This package supports 'rewrites'?
If don't, there are reasons (or issues) to support it?

**Comment by tatethurston** [comment]
Rewrites in next.config.js https://nextjs.org/docs/api-reference/next.config.js/rewrites?

**Comment by erickriva** [comment]
yeah, i'd like to generate types using aliases instead of original routes... is it supported?

**Comment by tatethurston** [comment]
This isn’t supported in the current version. Could you share an example with me and the outcome you would like?

**Comment by erickriva** [comment]
in my `next.config.js`, i have something like this:

```
module.exports = {
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: '/loja',
          destination: '/store',
        },
      ]
    }
  }
}
```

in this case, the folder inside `pages` directory is called `store` for a better organization purpose, so there is a `/store` route, right?
but i'm doing a `map` on `next.config.js` to `/loja` (_**store**_ in my language, portuguese)

i want the types to have `/loja` instead of `/store`...
is this doable?

**Comment by tatethurston** [comment]
I see, so you would want the generated route type for something like

`/store/[id]/` to instead be `/loja/[id]`?

And this is because you want your public facing URL paths to be in english, but your source code to be in Portuguese?

**Comment by erickriva** [comment]
> And this is because you want your public facing URL paths to be in english, but your source code to be in Portuguese?

I need the folder names to be in English, but routes must be in Portuguese.
The `Next` part of it was already made, setting the map of rewrites on `next.config.js`.
But the typing keeps using folder name as route path. Can't it look to `next` config file and map to these new routes?

**Comment by tatethurston** [comment]
> But the typing keeps using folder name as route path. Would be possible to look to next config file and map to these new routes?

The scope for parsing the `next.config.js` would get large quite quickly. [rewrites accept arbitrary regex patterns](https://nextjs.org/docs/api-reference/next.config.js/rewrites#regex-path-matching) and also [path-to-regexp](https://github.com/pillarjs/path-to-regexp) strings.

Could you help me understand the english naming constraint more? It seems like you could move the folder to something like `src/en-pages/store` and then inside `page/loja` you would have:

```
export * from './src/en-pages/store';
```

I'll keep this open to see if others have a similar need, but in the meantime you could write a script to replace `store` with `loja` in the generated `nextjs-routes.d.ts`.

**Comment by erickriva** [comment]
Oh, I understand your concerns, it makes much sense... There's an update being prepared for router, isn't?
Maybe it will be solved (or at least a part of) in that update.
Would be great if this package was 'absorbed' by Next, to be a default type generator for router.
Thank you for your answers! It was really helpful 😊

**Comment by tatethurston** [comment]
No problem! I’ll look into next pathname intl more, it would be great to have a canonical system for the next ecosystem

**Comment by jonkwheeler** [comment]
I did this....

```
// nextjs-additional-routes.d.ts

declare module 'nextjs-routes' {
  export type Route =
    | StaticRoute<'/rewrite/1'>
    | StaticRoute<'/rewrite/2'>
    | import('nextjs-routes').Route
}

```

@tatethurston you could add this to the README?

**Comment by tatthurs** [comment]
@jonkwheeler I'm happy you found a workaround that works for you. I'm hesitant to add this to the README as a suggested solution.
