### ISSUE TITLE
parallel and Intercepting Routes Support 

### ISSUE THREAD

**Issue by mrhut10** [tatethurston/nextjs-routes#194]
Currently utilizing plenty of [parallel](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) and [intercepting](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes) routes,

I believe they end up getting typed in using this package wrong.

where we see routes like `/app/blog/@modals/(.)/delete`

I suspect we need to ignore the `@` segments, when building routes,
then pop segments off based on the [convention](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes#convention) in nextjs documentation

I'm happy to contribute towards this, but might be good to confirm that I'm correct in my assumption/believe what needs doing.

**Comment by tatethurston** [comment]
Thanks for reporting this and opening a PR. I've published this in nextjs-routes@2.2.2-rc.3 -- LMK if you encounter any issues!
