### ISSUE TITLE
The Link doesn't accept dynamic routes as href

### ISSUE THREAD

**Issue by KingMatrix1989** [tatethurston/nextjs-routes#198]
I am using the latest version of the package and seems the Next Link component doesn't accept any dynamic route as `href` while I don't have the same issue with `useRouter`.

Here are the generated types:
```ts
 // ...
  type StaticRoute = Exclude<Route, { query: any }>["pathname"];

  export interface LinkProps
    extends Omit<NextLinkProps, "href" | "locale">,
      AnchorHTMLAttributes<HTMLAnchorElement> {
    href: StaticRoute | RouteLiteral;
    locale?: false;
  }

  type LinkReactElement = DetailedReactHTMLElement<
    {
      onMouseEnter?: MouseEventHandler<Element> | undefined;
      onClick: MouseEventHandler;
      href?: string | undefined;
      ref?: any;
    },
    HTMLElement
  >;
```

According to the above code, the `href` type can be only `StaticRoute` or `RouteLiteral`!!! Why did you ignore dynamic routes?

![image](https://github.com/user-attachments/assets/7a30a6ea-93c0-4741-8407-d95ee0fa431d)

**Comment by tatethurston** [comment]
Which pre-release version are you using?
Are you using the app directory, the pages directory, or both?

**Comment by KingMatrix1989** [comment]
> @KingMatrix1989 could you provide the following context for me?
> 
> * nextjs-routes version:
> * Are you using the [pages](https://nextjs.org/docs/pages/building-your-application/routing) directory, [app](https://nextjs.org/docs/app/building-your-application/routing) directory, or both?
> * Are you using nextjs-routes via [next.config.js](https://github.com/tatethurston/nextjs-routes?tab=readme-ov-file#installation--usage-) or the CLI (`npx nextjs-routes`)?
> * nextjs version:

* nextjs-routes version: **2.2.2-rc.1** (installed by `yarn add nextjs-routes`)
* I'm using App Router
* the package enabled using `next.config.mjs`
* NextJS Version: **14.2.4**

**Comment by tatethurston** [comment]
@KingMatrix1989 Next.js' App Router doesn't accept dynamic hrefs: https://nextjs.org/docs/messages/app-dir-dynamic-href you need to use a path, so I'm confused about the ask here.

Was this working previously for you with nextjs-routes?

**Comment by KingMatrix1989** [comment]
> @KingMatrix1989 Next.js' App Router doesn't accept dynamic hrefs: https://nextjs.org/docs/messages/app-dir-dynamic-href you need to use a path, so I'm confused about the ask here.
> 
> * Could you show me an example of a Link you expect to be able to write but cannot?
> * Was this working previously for you with nextjs-routes?
> * Are you using `useRouter` from `next/navigation` or `next/router`? https://nextjs.org/docs/app/api-reference/functions/use-router.

Yeah, you are right. You said it in the README and I didn't notice :)

**Comment by tatethurston** [comment]
[v2.2.2-rc.4](https://github.com/tatethurston/nextjs-routes/releases/tag/v2.2.2-rc.4) is the latest version with app router support. I'll cut a non pre-release version of 2.2.2 here in the next week or two.
