### ISSUE TITLE
bug: useParams return type of RouteLiteral is being resolved as any

### ISSUE THREAD

**Issue by aqos156** [tatethurston/nextjs-routes#202]
**Describe the bug**
When `usePathname` is used within the codebase the return type `RouteLiteral` is being resolved to `any`.

![image](https://github.com/user-attachments/assets/53d9bb5a-6965-40c0-9fc5-3b825aa8e9ce)

However, everywhere else (that I have checked) the `RouteLiteral` is being resolved correctly.

![image](https://github.com/user-attachments/assets/fb4c1cda-78a7-4a37-98af-5071aa74a8c7)

**Workaround**

I have disabled generating types in production builds and manually removed the `usePathname` type override from `nextjs-routes.d.ts`. 

**Context (please complete the following information):**

- nextjs-routes version: 2.2.2
- Are you using the ~~[pages](https://nextjs.org/docs/pages/building-your-application/routing) directory,~~ [app](https://nextjs.org/docs/app/building-your-application/routing) directory ~~,or both?~~
- Are you using nextjs-routes via [next.config.js](https://github.com/tatethurston/nextjs-routes?tab=readme-ov-file#installation--usage-) ~~or the CLI (`npx nextjs-routes`)?~~
- nextjs version: 14.2.14

**Comment by tatethurston** [comment]
@aqos156 Thanks for reporting this bug -- that was quite the oversight on my end. I've updated the specs to catch this and published v2.2.3 with the fix.
