### ISSUE TITLE
bug: undefined query parameters are added to URLSearchParams

### ISSUE THREAD

**Issue by sleepdotexe** [tatethurston/nextjs-routes#206]
**Describe the bug**
When using the `route()` function, `undefined` values in the `query` object are added to the URLSearchParams as `param=undefined`.

A simple example:
```ts
const possibleQueryParam1: string | undefined = "param1";
const possibleQueryParam2: string | undefined = undefined;

return (
  <Link
    href={route({
      pathname: "/",
      query: {
        param1: possibleQueryParam1,
        param2: possibleQueryParam2,
      },
    })}
  >
    Go home
  </Link>
);
```

This is maybe open to discussion, but I would expect that the link would have an href of `/?param1=param1` given that there is no actual value for `param2`. However in reality, the href is `/?param1=param1&param2=undefined`.

It would make more sense to me for the `route()` function to automatically strip any undefined values, forcing the user to explicity include them by converting them to a string. Otherwise, any time I am including a dynamic value that may be undefined, I have to do a conditional check to ensure it doesn't get included in the href.

Taking a look at the code, this could likely be easily solved [here](https://github.com/tatethurston/nextjs-routes/blob/8231dbd921f001c7313abf948c42d645c372cb26/packages/nextjs-routes/src/index.ts#L64) by including a check to ensure that `value` is actually defined.

Something like this I think should work:
```diff
  const search = new URLSearchParams();
  for (const key in r.query) {
    if (!params.has(key)) {
      const value = r.query[key];
+     if(value === undefined) continue;
      if (Array.isArray(value)) {
        value.forEach((val) => search.append(key, val));
      } else {
        search.append(key, value as string);
      }
    }
  }
```

**Context (please complete the following information):**

- nextjs-routes version:
^2.2.3
- Are you using the [pages](https://nextjs.org/docs/pages/building-your-application/routing) directory, [app](https://nextjs.org/docs/app/building-your-application/routing) directory, or both?
/app
- Are you using nextjs-routes via [next.config.js](https://github.com/tatethurston/nextjs-routes?tab=readme-ov-file#installation--usage-) or the CLI (`npx nextjs-routes`)?
next.config.js
- nextjs version:
^14.2.13

**Comment by tatethurston** [comment]
Thanks for reporting @sleepdotexe. That's what I get for using a cast 😆
