### ISSUE TITLE
V1

### ISSUE THREAD

**Issue by tatethurston** [tatethurston/nextjs-routes#44]
Now that the API has begun to stabilize, we should consider what (if anything) should be added before releasing a v1. That release will mark the adoption of semantic versioning, to make it easier for users to reason about updates.

**Comment by alexgorbatchev** [comment]
If the API is stable, just release 1.0. If there are changes, release 2.0 :) Personally I really dislike when packages stay in 0.x for years, while being used in production just the same :)

**Comment by tatethurston** [comment]
Agreed
