### ISSUE TITLE
?query=string - how to?

### ISSUE THREAD

**Issue by OnkelTem** [tatethurston/nextjs-routes#46]
I'm trying to understand how nextjs-route can handle `?query=part`? 
For example, we have a page with a table that is supposed to be paged. So I need to pass count and page for every URL.
But nextjs-routes Router doesn't know about our params and I get errors.

**Comment by tatethurston** [comment]
Use query https://nextjs.org/docs/api-reference/next/link#with-url-object

**Comment by OnkelTem** [comment]
@tatethurston That seems to be an example of using `<Link>`, but what about `useRouter`?

```ts
const Home = () => {
  const router = useRouter<'/'>()
  const {
    query: { current = 0 },
  } = router

  // ...

  const onPagination = (pagination: TablePaginationConfig) => {
    const { current, pageSize } = pagination
    router.push(
      { query: { current: current?.toString(), pageSize: pageSize?.toString() } },
      undefined,
      { shallow: true }
    )
  }

```

The last part is erroneous, as the query (of the "/" page) doesn't know anything about my parameters. This is how it's generated:

```ts
declare module "nextjs-routes" {
  export type Route =
    // ...
    | { pathname: "/"; query?: Query | undefined }
    // ...
}
```

What do I do in this case?
Thanks in advance.

**Comment by tatethurston** [comment]
@OnkelTem your example for `useRouter` should work. What issue are you running into? Are you using version `0.0.18`?

**Comment by OnkelTem** [comment]
> Your example for router.push should work. What issue are you running into? Are you using version 0.0.18?

Yes, 0.0.18.
Ok, it seems that I want more than it can actually provide, or made for.
What you mean under working - is that it compiles, while I want routes typing. Sure, the query is defined as a combination of anything in NextJS: its default `string | string[] | undefined` is inconvenient. E.g. one has to make some silly checks like `Array.isArray()` to get rid of the `string[]` part (what `nextjs-routes` fixes for queries defined in URL like `/[thing]/[thing]/...`). 
I could, once again, extend the generated `.d.ts` to define my own type:

```ts
     | { pathname: "/"; query?: Query<{ current?: string, pageSize?: string }> | undefined }
```

but then I should disable its generation.

Ok, I understand now the limitation of this approach and I think we could really maintain some alternative to nextjs-routes.d.ts with our own types and extended functionality.

**Comment by tatethurston** [comment]
Types for search parameters are something we’re looking looking into https://github.com/tatethurston/nextjs-routes/issues/39
