### ISSUE TITLE
Semicolons are used where a comma should be used

### ISSUE THREAD

**Issue by OliverDudgeon** [tatethurston/nextjs-routes#48]
For me, the generated output has `;`s instead of `,`s to separate object entries which is incorrect and errors.

```
export type Route =
    | { pathname: "/api/dataset/[datasetId]/[datasetVersion]"; query: Query<{ datasetId: string; datasetVersion: string }> }
    | { pathname: "/api/project/[projectId]/file"; query: Query<{ projectId: string }> }
…
```

using `v0.0.18`

**Comment by tatethurston** [comment]
Properties are separated by semicolons not commas in TypeScript type declarations https://www.typescriptlang.org/docs/handbook/2/objects.html.

**Comment by tatethurston** [comment]
If you share more about the error you’re encountering, I may be able to help point you in the right direction.

**Comment by OliverDudgeon** [comment]
Apologies what I thought was an error here was a result of #49
