### ISSUE TITLE
Catch-all routes aren't generated right when the name isn't a valid JS identifier but is a valid NextJS route

### ISSUE THREAD

**Issue by OliverDudgeon** [tatethurston/nextjs-routes#49]
If I have an route which catches all subpaths such as `"/api/as-api/[...as-proxy]"` the generated route is `{ pathname: "/api/as-api/[...as-proxy]"; query: Query<{ as-proxy: string[] }> }`. Notice that there is a key, `as-proxy`, which is missing quotes to allow it to be a valid object key. 

Using `v0.0.18`

**Comment by tatethurston** [comment]
Thanks for reporting this @OliverDudgeon.

Thinking on the solution, we could quote all user supplied segments, or try to determine the subset that aren’t valid JS identifiers.

**Comment by tatethurston** [comment]
As a work around in the meantime, is anything stopping you from using `asProxy` instead of `as-proxy`?

**Comment by OliverDudgeon** [comment]
Nothing preventing this for me
