### ISSUE TITLE
Hash in `Link`'s `href` is not allowed

### ISSUE THREAD

**Issue by Elindorath** [tatethurston/nextjs-routes#85]
Hi there,

As I build up my codebase, I came on the use case of having a link with a hash to open a page scrolled on a specific id. While the original `next/link` component supports it (with the help of the `scroll` prop), the routes type definition generated by `nextjs-routes` prevents it as there is no hash possible in `pathname`.

I think this could be addressed with template literal string, but I wonder what do you think of it?

**Comment by tatethurston** [comment]
My inclination would be to cast or use next/link directly for the few call sites where this comes up.

I’m happy to look at a PR that investigates the template literal approach.

**Comment by tatethurston** [comment]
@Elindorath I missed that this was previously not possible with the UrlObject form. This has been fixed. Now you can do the following:

  ```tsx
  // this will link to /foo#bar
  <Link href={{ pathname: "/foo", hash: "bar" }}>Foo</Link>
  ```
