### ISSUE TITLE
Add support for Next.js app structure

### ISSUE THREAD

**Issue by IgnusG** [tatethurston/nextjs-routes#86]
Next.js 13 is now out and it released the new layout system under the new `app` folder.

Is it something this package is interested in adopting?

> The route structure is slightly different in that folder and both `app` and `pages` can be used at the same time so the tool would have to be able to merge the two route structures.

**Comment by tatethurston** [comment]
Yes this is definitely something I intend to support. Good call out on supporting both directories at the same time. I think the only remaining piece is checking out the next documentation to get the list of filenames / directories to exclude (eg layouts).

**Comment by tatethurston** [comment]
This has been released in 0.1.7
