### ISSUE TITLE
doesn't work for `src/pages` directory

### ISSUE THREAD

**Issue by sachinraja** [tatethurston/nextjs-routes#9]
Hey, thanks for the amazing project! In my app I use the [`src/pages` directory](https://nextjs.org/docs/advanced-features/src-directory) but it doesn't work for `nextjs-routes` because it only looks in the `pages` directory.

**Comment by tatethurston** [comment]
Hey @sachinraja thanks for reporting this. I just published v0.0.9 to enable this -- let me know if you run into any issues or have other ideas for improvement!

**Comment by sachinraja** [comment]
Wow that was fast! Works great now. One idea - it would be great to have an ESM build because the CJS build generates [a lot of cruft](https://unpkg.com/browse/nextjs-routes@0.0.9/link.js). Will definitely let you know if I have any more ideas, but it's been very nice to work with so far.

**Comment by tatethurston** [comment]
@sachinraja Thanks for pointing that out -- that was a silly oversight on my end. Now publishing ESM in v0.0.10

**Comment by tatethurston** [comment]
@sachinraja the mjs extension is a proposal but not a requirement for consuming ESM. If you use a bundler like webpack, roll up or vite the ESM export will be picked up out of the box.

**Comment by sachinraja** [comment]
The other libraries are incorrect. The bundlers are also incorrect but are forgiving because libraries are usually incorrect. It will break in cases like testing, where files are not bundled and just run through Node.

**Comment by tatethurston** [comment]
Nextjs default webpack config will correctly pick up this ESM so is there a particular outcome you’re unable to achieve here?

**Comment by sachinraja** [comment]
> nodejs will also handle ESM without the mjs extension when the package json type is set to module

This is on a per-package basis. So `"type": "module"` would have to be set in this project for that to work. Anyway, it's alright.

**Comment by tatethurston** [comment]
@sachinraja Ah, you’re right I see what you’re saying. Is there a reason to prefer publishing .mjs over setting type: module for this package (other than support for nodejs runtimes that predate that package.json key)?

**Comment by sachinraja** [comment]
Well if you set type:module you'll have to use `.cjs` extensions for commonjs. See https://nodejs.org/api/packages.html#determining-module-system

**Comment by tatethurston** [comment]
@sachinraja closing the loop on this, this library now ships ESM exclusively. I did some testing in the nextjs examples and couldn't find a need for cjs, but if you run into one LMK and I'll add a cjs export.

**Comment by sachinraja** [comment]
Thanks! I'll let you know if we run into any issues.
