### ISSUE TITLE
Change locale and stay on the same route

### ISSUE THREAD

**Issue by groomain** [tatethurston/nextjs-routes#96]
Hi,

I tried to change the locale and stay on the same route by following nextjs exemple.

```
const router = useRouter()
const { pathname, asPath, query } = router
// change just the locale and maintain all other route information including href's query
router.push({ pathname, query }, asPath, { locale: nextLocale })
```

Unfortunately I have a typescript error with nextjs-routes.

I fixed it with an assertion any but maybe you have a better solution?

Thanks for your help!

**Comment by tatethurston** [comment]
@groomain could you share your next.config.js?

**Comment by tatethurston** [comment]
@groomain Thanks, and the TypeScript error?

**Comment by tatethurston** [comment]
Could you paste the TypeScript error exactly as output by the compiler?

**Comment by groomain** [comment]
```
No overload matches this call.
  Overload 1 of 3, '(url: Route, as?: string | undefined, options?: TransitionOptions | undefined): Promise<boolean>', gave the following error.
    Argument of type '{ pathname: "/route-a" | "route-b" | more ... | "/[...slug]">; }' is not assignable to parameter of type 'Route'.
      Type '{ pathname: "/route-a" | "route-b" | more ... | "/[...slug]">; }' is not assignable to type '{ pathname: "/route-a"; query?: { [key: string]: string | string[] | undefined; } | undefined; }'.
        Types of property 'pathname' are incompatible.
          Type '"/route-a" | "route-b" | "/[...slug]"' is not assignable to type '"/route-a"'.
            Type '"/a-word"' is not assignable to type '"/route-a"'.
  Overload 2 of 3, '(url: "/route-a" | "route-b", as?: string | undefined, options?: TransitionOptions | undefined): Promise<...>', gave the following error.
    Argument of type '{ pathname: "/route-a" | "route-b" | more ... | "/[...slug]">; }' is not assignable to parameter of type '"/route-a" | "route-b"'.
  Overload 3 of 3, '(url: { query: { [key: string]: string | string[] | undefined; }; }, as?: string | undefined, options?: TransitionOptions | undefined): Promise<boolean>', gave the following error.
    Argument of type '{ pathname: "/route-a" | "route-b" | more ... | "/[...slug]">; }' is not assignable to parameter of type '{ query: { [key: string]: string | string[] | undefined; }; }'.
      Object literal may only specify known properties, and 'pathname' does not exist in type '{ query: { [key: string]: string | string[] | undefined; }; }'.
```

**Comment by tatethurston** [comment]
Thanks @groomain, this looks like a bug. Is this project publicly available in GitHub? If not, could you let me know:
- if you're using the pages or app directory?
- the version of nextjs-routes you're using

Could you also paste your generated nextjs-routes.d.ts?

**Comment by groomain** [comment]
if you're using the pages or app directory?
the version of nextjs-routes you're using

no sorry it's a private project
it's used with page folder  and the last version of nextjs-routes

**Comment by tatethurston** [comment]
@groomain I'm not able to reproduce this issue. Here's a working example using the code you've shared: https://stackblitz.com/edit/nextjs-8akbqz?file=next.config.js,package.json,pages%2Froute-a.tsx,pages%2F_app.tsx

Did you define your `locales` correctly? They need to be nested under `i18n`: https://nextjs.org/docs/advanced-features/i18n-routing

https://stackblitz.com/edit/nextjs-8akbqz?file=next.config.js,package.json,pages%2Froute-a.tsx,pages%2F_app.tsx

**Comment by groomain** [comment]
Hi,

Can you try this one ?
I think it's because I have a "catching all" page. [...slug].tsx

I've reproduced the error here.
https://stackblitz.com/edit/nextjs-zmkzrf?file=pages/_app.ts

**Comment by tatethurston** [comment]
Ah good find. I'll dig in here to look to see if I can make the types better accommodate this case.

In the meantime, you can supply a generic argument to useRouter to prevent this issue:
https://github.com/tatethurston/nextjs-routes#query

Example: https://stackblitz.com/edit/nextjs-t5pjth?file=pages%2Froute-a.tsx,pages%2F[...slug].tsx

**Comment by tatethurston** [comment]
On v1.0.1 you can do the following, because pathname and query will be pulled off router correctly, without the TypeScript destructuring tracking issue discussed above:

```
router.push(router, undefined, { locale: "fr" })
```
or for more intent clarity:

```
// nextjs will load the current route if pathname is omitted
router.push({ query: router.query }, undefined, { locale: "fr" })
```

**Comment by groomain** [comment]
Thanks ! 
#97 
fixed !
