### ISSUE TITLE
Incorrect Typing of Props for Link in next 13

### ISSUE THREAD

**Issue by litewarp** [tatethurston/nextjs-routes#99]
In nextj 13, `NextLink` [accepts anchor props](https://beta.nextjs.org/docs/api-reference/components/link). However, adding className to NextLink after installing `nextjs-routes` results in a type error. that `className` is not an acceptable prop. 

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/1900476/202932883-9182dae4-2e07-4df5-a264-b5e7f9725d04.png">

next-themes v 1.0.1
node 18
next 13.0.4

**Comment by tatethurston** [comment]
@litewarp Thanks for reporting this. I've updated the types in 1.0.2.

**Comment by erickriva** [comment]
From version 13.0.2, Next has a experimental flag to have typed routes in `app` folder.
In `next.config.js`, add  `experimental: {
    appDir: true,
    typedRoutes: true
 }`

**Comment by tatethurston** [comment]
Now supported in [2.2.2](https://www.npmjs.com/package/nextjs-routes/v/2.2.2)
